import {applyFilters,buildGroups,emptyGame,formatDecimal,formatPlayCount,hashPin,makeId,searchGames,sortGames,validateGame,validateExpansion} from "./domain.js";
import {clearDraft,createBackupPayload,deleteImage,downloadBackup,getImage,loadDraft,loadState,putImage,readBackupFile,restoreBackup,saveDraft,saveState,summarizeBackup} from "./storage.js";

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const blank=v=>v===null||v===undefined||v==="", num=v=>v===""?null:Number(v), clone=structuredClone;
const decimalInput=v=>blank(v)?"":formatDecimal(v);
const GROUP={itemType:"条目类型",collectionType:"收藏子类",designSchool:"设计流派",mechanisms:"设计机制",interaction:"互动结构",themes:"主题",owned:"购入状态",rated:"评分状态",hasExpansions:"扩展状态"};
const SORT={name:"名称",weight:"BGG 重度",rating:"个人评分",price:"购入价",plays:"开局数",playerMin:"推荐最少人数",playerMax:"推荐最多人数",createdAt:"创建时间",updatedAt:"最近修改"};
const TAX={itemType:"条目类型",collectionType:"收藏子类",designSchool:"设计流派",mechanisms:"设计机制",interaction:"互动结构",themes:"主题"};
const FILTER={
 itemType:["条目类型","single","itemType"],collectionType:["收藏子类","single","collectionType"],name:["名称","text"],version:["版本","text"],designSchool:["设计流派","single","designSchool"],mechanisms:["设计机制","multi","mechanisms"],themes:["主题","multi","themes"],interaction:["互动结构","single","interaction"],
 weight:["BGG 重度","number"],rating:["个人评分","number"],price:["购入价","number"],plays:["开局数","number"],playerMin:["推荐最少人数","number"],playerMax:["推荐最多人数","number"],
 owned:["购入状态","bool"],rated:["评分状态","bool"],hasExpansions:["扩展状态","bool"]
};
let state,editing=false,openId=null,openGroup=null,openExp=null,draft=null,isNew=false,dirty=false,timer,tempFilters=[],taxTab="designSchool",pending=new Set(),ambientUrl,undo;
const E={collection:$("#collection"),count:$("#collectionCount"),search:$("#searchInput"),group:$("#groupSelect"),sort:$("#sortSelect"),direction:$("#sortDirectionButton"),filters:$("#activeFilters"),ambient:$("#ambientCover"),scrim:$("#drawerScrim"),toast:$("#toastRegion")};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${({x:'<path d="m6 6 12 12M18 6 6 18"/>',plus:'<path d="M12 5v14M5 12h14"/>',image:'<rect x="4" y="5" width="16" height="14" rx="2"/><path d="m5 17 4-4 3 3 2-2 5 4"/>',trash:'<path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7"/>',edit:'<path d="m4 20 4-1 10-10-3-3-10 10-1 4Z"/>',weight:'<path d="M5 19h14M7 16l2-8h6l2 8M10 8V5h4v3"/>',heart:'<path d="M12 20s-7-4.4-7-10a4 4 0 0 1 7-2.7A4 4 0 0 1 19 10c0 5.6-7 10-7 10Z"/>',cart:'<circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M3 4h2l2.4 11.2a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 2-1.6L21 8H6"/>',play:'<path d="m8 5 11 7-11 7Z"/>',chev:'<path d="m7 9 5 5 5-5"/>'})[n]||""}</svg>`;
function toast(msg,label,fn){const n=document.createElement("div");n.className="toast";n.innerHTML=`<span>${esc(msg)}</span>${label?`<button>${esc(label)}</button>`:""}`;if(label)$("button",n).onclick=()=>{fn?.();n.remove()};E.toast.append(n);setTimeout(()=>n.remove(),6500)}
function options(){E.group.innerHTML=Object.entries(GROUP).map(([v,l])=>`<option value="${v}">${l}</option>`).join("");E.sort.innerHTML=Object.entries(SORT).map(([v,l])=>`<option value="${v}">${l}</option>`).join("");E.group.value=state.view.groupBy;E.sort.value=state.view.sortBy;E.search.value=state.view.search;direction()}
function direction(){const a=state.view.sortDirection==="asc";E.direction.style.transform=a?"":"rotate(180deg)";E.direction.ariaLabel=a?"当前升序，点击改为降序":"当前降序，点击改为升序"}
function dial(kind,v,max){const empty=blank(v),p=empty?0:Math.max(0,Math.min(100,Number(v)/max*100)),value=formatDecimal(v),label=`${kind==="weight"?"BGG 重度":"个人评分"} ${empty?"未填写":value}`;return `<span class="rating-readout ${empty?"is-empty":""}" aria-label="${label}" title="${label}"><span class="rating-gauge" aria-hidden="true"><svg class="rating-dial" viewBox="0 0 40 40"><path class="rating-track" d="M 8.69 31.31 A 16 16 0 1 1 31.31 31.31" pathLength="100"/><path class="rating-fill" d="M 8.69 31.31 A 16 16 0 1 1 31.31 31.31" pathLength="100" stroke-dasharray="${p} 100" ${p===0?'visibility="hidden"':""}/></svg><span class="rating-icon">${icon(kind==="weight"?"weight":"heart")}</span></span><span class="rating-number" aria-hidden="true">${value}</span></span>`}
function cover(id,alt,size="thumbnail"){return id?`<div class="cover-frame"><div class="cover-frame__blur" data-image-id="${esc(id)}" data-image-size="${size}" data-bg></div><img class="cover-frame__image" data-image-id="${esc(id)}" data-image-size="${size}" alt="${esc(alt)}"></div>`:`<div class="cover-frame"><div class="cover-placeholder">${icon("image")}</div></div>`}
async function images(root=document){await Promise.all($$("[data-image-id]",root).map(async n=>{if(n.dataset.done)return;n.dataset.done=1;const b=await getImage(n.dataset.imageId,n.dataset.imageSize);if(!b)return;const u=URL.createObjectURL(b);if(n.tagName==="IMG"){n.src=u;n.onload=()=>URL.revokeObjectURL(u)}else n.style.backgroundImage=`url("${u}")`}))}
const fact=(l,v)=>`<div class="fact"><span>${l}</span><strong>${esc(blank(v)?"—":v)}</strong></div>`;
function titleClass(name){const length=[...String(name||"")].length;return length>24?"is-very-long":length>14?"is-long":""}
function card(g,key){const collection=g.itemType==="collection",school=collection?"收藏":g.designSchool,tags=(collection?[g.collectionType]:g.mechanisms||[]).filter(Boolean),owned=blank(g.price)?"未购入":"已购入";return `<article class="game-card"><button class="game-card__button" data-act="open" data-id="${g.id}" data-group="${esc(key)}" aria-expanded="${openId===g.id}">${cover(g.coverId,g.name)}<div class="game-card__body"><h3 class="game-card__title ${titleClass(g.name)}" title="${esc(g.name)}">${esc(g.name)}</h3>${collection?'<div class="rating-pair rating-pair--empty" aria-hidden="true"></div>':`<div class="rating-pair">${dial("weight",g.weight,5)}${dial("rating",g.rating,10)}</div>`}<div class="card-status"><span>${icon("cart")}${owned}</span>${collection?"":`<span>${icon("play")}${formatPlayCount(g.plays)}</span>`}</div><div class="game-tags game-tags--card"><div class="card-school">${school?`<span class="game-tag game-tag--school">${esc(school)}</span>`:""}</div><div class="card-mechanisms">${tags.map(t=>`<span class="game-tag" title="${esc(t)}">${esc(t)}</span>`).join("")}</div></div></div></button></article>`}
function exps(g){if(!g.expansions?.length)return `<p class="stage-notes">暂无扩展。</p>`;return `<div class="expansion-grid">${g.expansions.map(e=>`<button class="expansion-card" data-act="exp" data-id="${e.id}" aria-expanded="${openExp===e.id}"><img data-image-id="${e.coverId}" data-image-size="thumbnail" alt="${esc(e.name)}封面"><strong>${esc(e.name)}</strong></button>${openExp===e.id?`<div class="expansion-detail"><img data-image-id="${e.coverId}" data-image-size="original" alt=""><div><h3>${esc(e.name)}</h3><div class="fact-grid">${fact("购入价",blank(e.price)?"未购入":`¥ ${formatDecimal(e.price)}`)}${fact("个人评分",formatDecimal(e.rating))}</div><div class="stage-section"><h3>备注</h3><p class="stage-notes">${esc(e.notes||"—")}</p></div></div></div>`:""}`).join("")}</div>`}
function viewStage(g){const collection=g.itemType==="collection",people=blank(g.playerMin)?"—":g.playerMin===g.playerMax?`${g.playerMin} 人`:`${g.playerMin}–${g.playerMax} 人`,tags=(collection?["收藏类",g.collectionType,...(g.themes||[])]:[g.designSchool,g.interaction,...(g.mechanisms||[]),...(g.themes||[])]).filter(Boolean);return `<article class="game-stage" data-stage-id="${g.id}"><div class="stage-grid"><div class="stage-cover">${cover(g.coverId,g.name,"original")}</div><div class="stage-content"><div class="stage-head"><div class="stage-title"><h2>${esc(g.name)}</h2><p>${esc(g.version||g.collectionType||"")}</p></div><div class="stage-actions">${editing?`<button class="primary-button" data-act="edit">${icon("edit")}编辑这款${collection?"收藏品":"游戏"}</button>`:""}<button class="square-button" data-act="close" aria-label="收起">${icon("x")}</button></div></div>${collection?"":`<div class="stage-rating">${dial("weight",g.weight,5)}${dial("rating",g.rating,10)}</div>`}<div class="fact-grid">${fact("购入状态",blank(g.price)?"未购入":`¥ ${formatDecimal(g.price)}`)}${collection?"":`${fact("开局数",formatPlayCount(g.plays))}${fact("推荐人数",people)}${fact("扩展",`${g.expansions?.length||0} 个`)}`}</div><div class="stage-section"><h3>分类</h3><div class="game-tags">${tags.map((t,i)=>`<span class="game-tag ${i?"":"game-tag--school"}">${esc(t)}</span>`).join("")||"—"}</div></div><div class="stage-section"><h3>备注</h3><p class="stage-notes">${esc(g.notes||"—")}</p></div></div></div>${collection?"":`<section class="expansion-section"><div class="expansion-head"><h3>扩展</h3></div>${exps(g)}</section>`}</article>`}
const field=(l,n,v,o={})=>`<label class="editor-field ${o.wide?"editor-field--wide":""} ${o.full?"editor-field--full":""}"><span>${l}${o.req?" · 必填":""}</span><input name="${n}" type="${o.type||"text"}" value="${esc(blank(v)?"":v)}" ${o.min!==undefined?`min="${o.min}"`:""} ${o.max!==undefined?`max="${o.max}"`:""} ${o.step?`step="${o.step}"`:""}></label>`;
function chips(name,list,selected,multi=false,max=""){return `<div class="option-grid" data-options="${name}" data-multi="${multi}" data-max="${max}">${list.map(v=>`<button class="option-chip" data-act="option" data-field="${name}" data-value="${esc(v)}" aria-pressed="${multi?selected?.includes(v):selected===v}">${esc(v)}</button>`).join("")}</div>`}
function drop(id,path,label){return `<label class="image-drop" data-drop="${path}" tabindex="0">${id?`<img data-image-id="${id}" data-image-size="thumbnail" alt="${esc(label)}预览">`:`<span>${icon("image")}<br>选择、拖放或粘贴封面<br><small>保留原图并生成缩略图</small></span>`}<input type="file" accept="image/*" data-file="${path}"></label>`}
function expEditor(e,i){return `<div class="expansion-detail"><div>${drop(e.coverId,`exp:${e.id}`,e.name||"扩展")}</div><div class="editor-form"><div class="stage-head"><h3>扩展 ${i+1}</h3><button class="danger-button" data-act="del-exp" data-id="${e.id}">${icon("trash")}删除</button></div><div class="editor-grid">${field("名称",`exp.${e.id}.name`,e.name,{wide:true,req:true})}${field("购入价",`exp.${e.id}.price`,decimalInput(e.price),{type:"number",min:0,step:".01"})}${field("个人评分",`exp.${e.id}.rating`,decimalInput(e.rating),{type:"number",min:0,max:10,step:".01"})}<label class="editor-field editor-field--full"><span>备注</span><textarea name="exp.${e.id}.notes">${esc(e.notes||"")}</textarea></label></div></div></div>`}
function editorFields(g){const c=g.itemType==="collection";return `${field("条目名称","name",g.name,{wide:true,req:true})}${c?"":field("所属版本","version",g.version,{req:true})}${field("购入价","price",decimalInput(g.price),{type:"number",min:0,step:".01"})}${c?`<div class="editor-field editor-field--full"><span>收藏子类 · 必填</span>${chips("collectionType",state.taxonomies.collectionType,g.collectionType)}</div>`:`${field("BGG 重度","weight",decimalInput(g.weight),{type:"number",min:0,max:5,step:".01"})}${field("个人评分","rating",decimalInput(g.rating),{type:"number",min:0,max:10,step:".01"})}${field("开局数","plays",g.plays,{type:"number",min:0,step:"1"})}${field("推荐最少人数","playerMin",g.playerMin,{type:"number",min:1})}${field("推荐最多人数","playerMax",g.playerMax,{type:"number",min:1})}<div class="editor-field editor-field--full"><span>设计流派 · 必填</span>${chips("designSchool",state.taxonomies.designSchool,g.designSchool)}</div><div class="editor-field editor-field--full"><span>设计机制 · 最多 3 个</span>${chips("mechanisms",state.taxonomies.mechanisms,g.mechanisms,true,3)}</div><div class="editor-field editor-field--full"><span>互动结构</span>${chips("interaction",state.taxonomies.interaction,g.interaction)}</div>`}<label class="editor-field editor-field--full"><span>主题标签</span><input name="themes" value="${esc((g.themes||[]).join("，"))}"></label><label class="editor-field editor-field--full"><span>备注</span><textarea name="notes">${esc(g.notes||"")}</textarea></label>`}
function editor(g){const c=g.itemType==="collection";return `<article class="game-stage" data-stage-id="${g.id}"><form id="gameEditor" class="editor-form" novalidate><div class="stage-grid"><div class="stage-cover">${drop(g.coverId,"game",g.name||"条目")}</div><div class="stage-content"><div class="stage-head"><div class="stage-title"><h2>${isNew?"添加收藏条目":esc(g.name||"未命名")}</h2><p>草稿自动保存在当前浏览器</p></div><button class="square-button" data-act="cancel" aria-label="取消">${icon("x")}</button></div><div id="editorErrors"></div><div class="editor-grid"><div class="editor-field editor-field--full"><span>条目类型 · 必填</span>${chips("itemType",["桌游","收藏类"],c?"收藏类":"桌游")}</div>${editorFields(g)}</div><div class="stage-savebar"><span id="saveStatus" class="save-status">${dirty?"草稿已保存":"尚未修改"}</span><div class="save-actions">${isNew?"":`<button class="danger-button" data-act="del-game">${icon("trash")}删除</button>${c?"":`<button class="secondary-button" data-act="plus-play">${icon("plus")}1 局</button>`}`}<button class="ghost-button" data-act="cancel">取消</button><button class="primary-button" type="submit">保存修改</button></div></div></div></div>${c?"":`<section class="expansion-section"><div class="expansion-head"><h3>扩展</h3><button class="secondary-button" data-act="add-exp">${icon("plus")}添加扩展</button></div><div class="expansion-grid">${g.expansions.map((e,i)=>`<button class="expansion-card" data-act="edit-exp" data-id="${e.id}" aria-expanded="${openExp===e.id}"><span class="cover-placeholder">${icon("image")}</span><strong>${esc(e.name||"未命名扩展")}</strong></button>${openExp===e.id?expEditor(e,i):""}`).join("")}</div></section>`}</form></article>`}
function groupValues(g){const f=state.view.groupBy;if(["mechanisms","themes"].includes(f))return g[f]?.length?g[f]:["__empty"];if(f==="designSchool"&&g.itemType==="collection")return["收藏"];if(f==="itemType")return[g.itemType==="collection"?"收藏类":"桌游"];if(f==="collectionType")return[g.collectionType||"__empty"];if(f==="owned")return[blank(g.price)?"未购入":"已购入"];if(f==="rated")return[blank(g.rating)?"未评分":"已评分"];if(f==="hasExpansions")return[g.expansions?.length?"有扩展":"无扩展"];return[g[f]||"__empty"]}
function filtered(){try{return searchGames(applyFilters(state.games,state.view.filters),state.view.search)}catch(e){toast(e.message);return state.games}}
function render(){E.count.textContent=state.games.length;$("#addGameButton").hidden=!editing;$("#categoryButton").hidden=!editing;$("#editModeButton").classList.toggle("is-active",editing);$("#viewModeButton").classList.toggle("is-active",!editing);$("#filterCount").hidden=!state.view.filters.length;$("#filterCount").textContent=state.view.filters.length;E.filters.innerHTML=state.view.filters.map((f,i)=>`<span class="filter-chip">${esc(FILTER[f.field]?.[0])} · ${esc(f.operator)} ${esc(Array.isArray(f.value)?f.value.join("、"):f.value??"")}<button data-act="rm-filter" data-id="${i}">${icon("x")}</button></span>`).join("");const games=filtered(),groups=buildGroups(games,state.view.groupBy,state.taxonomies),newStage=isNew&&draft?`<section class="group"><div class="game-grid">${editor(draft)}</div></section>`:"";if(!state.games.length&&!newStage)E.collection.innerHTML=`<div class="empty-collection"><div><div class="empty-object"><span></span><span></span><span></span></div><h2>收藏柜还是空的</h2><p>从第一款桌游开始。封面会成为这面收藏墙的颜色和背景。</p><button class="primary-button" data-act="new">${icon("plus")}添加第一款桌游</button></div></div>`;else if(!games.length&&!newStage)E.collection.innerHTML=`<div class="empty-collection"><div><h2>没有符合条件的桌游</h2><p>调整搜索或筛选条件。</p><button class="secondary-button" data-act="clear-filter">清除搜索与筛选</button></div></div>`;else E.collection.innerHTML=newStage+groups.map(({key,games})=>{const gs=sortGames(games,state.view.sortBy,state.view.sortDirection),collapsed=state.view.collapsedGroups.includes(`${state.view.groupBy}:${key}`);return `<section class="group ${collapsed?"is-collapsed":""}" data-group="${esc(key)}"><div class="group-head"><div class="group-title"><h2>${esc(key==="__empty"?"未分类":key)}</h2><span>${gs.length} 件</span></div><button class="group-toggle" data-act="toggle-group">${icon("chev")}</button></div><div class="game-grid">${gs.map(g=>card(g,key)+(openId===g.id&&openGroup===key?(draft?.id===g.id?editor(draft):viewStage(g)):"")).join("")}</div></section>`}).join("");images(E.collection)}
async function ambient(g){if(ambientUrl)URL.revokeObjectURL(ambientUrl);ambientUrl=null;if(!g?.coverId){E.ambient.classList.remove("is-visible");return}const b=await getImage(g.coverId,"original");if(b){ambientUrl=URL.createObjectURL(b);E.ambient.style.backgroundImage=`url("${ambientUrl}")`;E.ambient.classList.add("is-visible")}}
async function openGame(id,key){draft=null;isNew=false;dirty=false;openExp=null;openId=id;openGroup=key;const g=state.games.find(x=>x.id===id);render();ambient(g);requestAnimationFrame(()=>$("[data-stage-id]")?.scrollIntoView({behavior:"smooth",block:"center"}))}
async function newGame(){if(!editing&&!(await unlock()))return;openId=null;draft=emptyGame();isNew=true;dirty=false;render();requestAnimationFrame(()=>$("[data-stage-id]")?.scrollIntoView({behavior:"smooth",block:"start"}))}
async function beginEdit(){const g=state.games.find(x=>x.id===openId);draft=clone(await loadDraft(g.id)||g);isNew=false;dirty=Boolean(await loadDraft(g.id));render()}
function readForm(){const f=$("#gameEditor");if(!f||!draft)return;const d=new FormData(f);["name","version","notes"].forEach(k=>draft[k]=String(d.get(k)||""));["price","weight","rating","plays","playerMin","playerMax"].forEach(k=>draft[k]=num(d.get(k)));draft.themes=String(d.get("themes")||"").split(/[，,]/).map(x=>x.trim()).filter(Boolean);draft.expansions.forEach(e=>{["name","notes"].forEach(k=>{const v=d.get(`exp.${e.id}.${k}`);if(v!==null)e[k]=String(v)});["price","rating"].forEach(k=>{const v=d.get(`exp.${e.id}.${k}`);if(v!==null)e[k]=num(v)})})}
function autosave(){dirty=true;clearTimeout(timer);timer=setTimeout(()=>saveDraft(draft.id,draft).then(()=>{$("#saveStatus")&&($("#saveStatus").textContent="草稿已保存")}),300)}
async function ask(title,body,label="确认",danger=false,html=false,valid){const d=$("#confirmDialog");$("#confirmTitle").textContent=title;$("#confirmBody").innerHTML=html?body:`<p>${esc(body)}</p>`;const b=$("#confirmAction");b.textContent=label;b.className=danger?"danger-button":"primary-button";d.showModal();return new Promise(r=>d.addEventListener("close",()=>{const ok=d.returnValue==="confirm";r(ok&&(!valid||valid()))},{once:true}))}
async function saveGame(){readForm();const errors=validateGame(draft);draft.expansions.forEach(e=>Object.assign(errors,validateExpansion(e)));if(Object.keys(errors).length){$("#editorErrors").innerHTML=`<div class="editor-errors">${Object.values(errors).map(esc).join("；")}</div>`;return}const dup=state.games.find(g=>g.id!==draft.id&&g.name.trim()===draft.name.trim()&&g.version.trim()===draft.version.trim());if(dup&&!await ask("发现相同名称与版本","仍要保存为独立条目吗？","仍然保存"))return;draft.updatedAt=new Date().toISOString();const i=state.games.findIndex(g=>g.id===draft.id);i<0?state.games.push(clone(draft)):state.games[i]=clone(draft);state.taxonomies.themes=[...new Set([...state.taxonomies.themes,...draft.themes])];await saveState(state);await clearDraft(draft.id);pending.clear();dirty=false;isNew=false;openId=draft.id;openGroup=groupValues(draft)[0];draft=null;options();render();toast("桌游已保存")}
async function cancel(){if(dirty&&!await ask("取消编辑？","正式收藏不会改变，未使用图片会被清理。","取消编辑",true))return;for(const id of pending)await deleteImage(id);pending.clear();draft&&await clearDraft(draft.id);const n=isNew;draft=null;dirty=false;isNew=false;if(n){openId=null;openGroup=null}render()}
async function close(){if(dirty&&!await ask("放弃未保存的修改？","请先保存或取消当前草稿。","继续编辑"))return;draft=null;isNew=false;dirty=false;openId=openGroup=openExp=null;ambient(null);render()}
async function image(file,path){try{const id=await putImage(file);pending.add(id);if(path==="game")draft.coverId=id;else{const e=draft.expansions.find(x=>x.id===path.split(":")[1]);if(e)e.coverId=id}autosave();render()}catch(e){toast(e.message)}}
async function unlock(){const setup=!state.security.pinHash,d=$("#pinDialog");$("#pinTitle").textContent=setup?"创建编辑密码":"进入编辑模式";$("#pinDescription").textContent=setup?"设置 6 位数字密码。用于防止误编辑，不会加密本地数据。":"输入 6 位数字密码解锁编辑。";$("#pinConfirmField").hidden=!setup;$("#pinInput").value=$("#pinConfirmInput").value="";$("#pinError").textContent="";d.dataset.setup=setup;d.showModal();return new Promise(r=>d.addEventListener("close",()=>r(editing),{once:true}))}
function openDrawer(d){$$(".drawer.is-open").forEach(x=>x.classList.remove("is-open"));d.classList.add("is-open");d.ariaHidden="false";E.scrim.hidden=false}
function closeDrawers(){$$(".drawer.is-open").forEach(x=>{x.classList.remove("is-open");x.ariaHidden="true"});E.scrim.hidden=true}
function defaultFilter(field){const t=FILTER[field][1];return{field,operator:t==="number"?"gte":t==="multi"?"any":t==="text"?"contains":"eq",value:t==="multi"?[]:t==="bool"?true:t==="single"?state.taxonomies[FILTER[field][2]][0]:""}}
function filterRows(){$("#filterRows").innerHTML=tempFilters.map((f,i)=>{const cfg=FILTER[f.field],type=cfg[1],ops=type==="number"?[["gte","大于等于"],["lte","小于等于"],["between","介于"],["empty","未填写"],["filled","已填写"]]:type==="multi"?[["any","命中任一"],["all","全部包含"],["empty","未填写"],["filled","已填写"]]:type==="text"?[["contains","包含"],["empty","未填写"],["filled","已填写"]]:[["eq","等于"]];let val="";if(!["empty","filled"].includes(f.operator)){if(type==="single")val=`<select data-fval>${state.taxonomies[cfg[2]].map(x=>`<option ${x===f.value?"selected":""}>${esc(x)}</option>`).join("")}</select>`;else if(type==="bool")val=`<select data-fval><option value="true" ${f.value===true?"selected":""}>是</option><option value="false" ${f.value===false?"selected":""}>否</option></select>`;else if(f.operator==="between")val=`<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input data-start type="number" value="${f.value?.[0]??""}"><input data-end type="number" value="${f.value?.[1]??""}"></div>`;else val=`<input data-fval type="${type==="number"?"number":"text"}" value="${esc(Array.isArray(f.value)?f.value.join("，"):f.value??"")}">`}return `<div class="filter-row" data-frow="${i}"><label><span>字段</span><select data-ffield>${Object.entries(FILTER).map(([k,c])=>`<option value="${k}" ${k===f.field?"selected":""} ${tempFilters.some((x,j)=>j!==i&&x.field===k)?"disabled":""}>${c[0]}</option>`).join("")}</select></label><label><span>条件</span><select data-fop>${ops.map(([v,l])=>`<option value="${v}" ${v===f.operator?"selected":""}>${l}</option>`).join("")}</select></label><button class="square-button" data-act="rm-temp">${icon("trash")}</button><label class="filter-value"><span>值</span>${val||"<small>不需要填写</small>"}</label></div>`}).join("");$("#addFilterButton").disabled=tempFilters.length>=3}
function readFilters(){tempFilters=$$("[data-frow]").map(r=>{const field=$("[data-ffield]",r).value,operator=$("[data-fop]",r).value,type=FILTER[field][1];let value=null;if(operator==="between")value=[num($("[data-start]",r).value),num($("[data-end]",r).value)];else if(!["empty","filled"].includes(operator)){value=$("[data-fval]",r)?.value||"";if(type==="number")value=num(value);if(type==="bool")value=value==="true";if(type==="multi")value=value.split(/[，,]/).map(x=>x.trim()).filter(Boolean)}return{field,operator,value}})}
const refs=(kind,label)=>state.games.reduce((n,g)=>n+(["designSchool","interaction","itemType","collectionType"].includes(kind)?(kind==="itemType"?(g.itemType==="collection"?"收藏类":"桌游"):g[kind])===label:g[kind]?.includes(label)?1:0),0);
function categories(){$("#categoryTabs").innerHTML=Object.entries(TAX).map(([k,l])=>`<button data-tab="${k}" role="tab" aria-selected="${taxTab===k}">${l}</button>`).join("");$("#categoryList").innerHTML=state.taxonomies[taxTab].map((l,i)=>`<div class="category-item" draggable="true" data-ci="${i}"><span>${icon("chev")}</span><span class="category-item__name">${esc(l)}</span><span class="category-item__count">${refs(taxTab,l)} 处引用</span><button data-act="rename-tax" data-label="${esc(l)}">${icon("edit")}</button><button data-act="merge-tax" data-label="${esc(l)}">${icon("chev")}</button><button data-act="delete-tax" data-label="${esc(l)}">${icon("trash")}</button></div>`).join("")}
function migrate(kind,from,to=""){state.games.forEach(g=>{if(["designSchool","interaction","collectionType"].includes(kind)){if(g[kind]===from)g[kind]=to}else if(kind==="itemType"){if((g.itemType==="collection"?"收藏类":"桌游")===from)g.itemType=to==="收藏类"?"collection":"tabletop"}else g[kind]=[...new Set((g[kind]||[]).map(x=>x===from?to:x).filter(Boolean))]})}
async function promptValue(title,text,initial=""){const body=`<p>${esc(text)}</p><label><span>名称</span><input id="promptValue" value="${esc(initial)}"></label>`;if(!await ask(title,body,"确认",false,true,()=>$("#promptValue").value.trim()))return null;return $("#promptValue").value.trim()}
async function exportNow(prefix="一桌一屏-备份"){state=await loadState();const p=await createBackupPayload(state);downloadBackup(p,prefix);state.meta.lastBackupAt=p.exportedAt;await saveState(state);backupStatus();return p}
function backupStatus(){$("#backupStatus").textContent=state.meta.lastBackupAt?`最近备份：${new Date(state.meta.lastBackupAt).toLocaleString("zh-CN")}`:"尚未备份"}
async function click(e){const a=e.target.closest("[data-act]");if(!a){const d=e.target.closest("[data-drop]");if(d)$("[data-file]",d).click();return}e.preventDefault();const t=a.dataset.act;
 if(t==="open")return openGame(a.dataset.id,a.dataset.group);if(t==="new")return newGame();if(t==="close")return close();if(t==="edit")return beginEdit();if(t==="cancel")return cancel();if(t==="exp"||t==="edit-exp"){openExp=openExp===a.dataset.id?null:a.dataset.id;return render()}
 if(t==="option"){const f=a.dataset.field,v=a.dataset.value,g=a.closest("[data-options]");if(g.dataset.multi==="true"){const s=new Set(draft[f]||[]);if(s.has(v))s.delete(v);else{if(Number(g.dataset.max)&&s.size>=Number(g.dataset.max))return toast(`最多选择 ${g.dataset.max} 个`);s.add(v)}draft[f]=[...s]}else draft[f]=draft[f]===v?"":(f==="itemType"?(v==="收藏类"?"collection":"tabletop"):v);if(f==="itemType"&&draft[f]==="collection"){draft.weight=draft.rating=draft.plays=draft.playerMin=draft.playerMax=null;draft.designSchool="";draft.mechanisms=[];draft.interaction=""}autosave();return render()}
 if(t==="add-exp"){readForm();const x={id:makeId("expansion"),name:"",coverId:"",price:null,rating:null,notes:""};draft.expansions.push(x);openExp=x.id;autosave();return render()}
 if(t==="del-exp"){if(await ask("删除扩展？","扩展将从草稿移除，保存桌游后生效。","删除扩展",true)){draft.expansions=draft.expansions.filter(x=>x.id!==a.dataset.id);openExp=null;autosave();render()}return}
 if(t==="plus-play"){readForm();const before=draft.plays;draft.plays=(draft.plays??0)+1;autosave();render();return toast("开局数已增加 1","撤销",()=>{draft.plays=before;autosave();render()})}
 if(t==="del-game"){const g=state.games.find(x=>x.id===draft.id),body=`<p>将删除“${esc(g.name)}”及其 ${g.expansions?.length||0} 个扩展。</p><label><span>输入桌游名称确认</span><input id="deleteName"></label>`;if(!await ask("删除桌游",body,"删除",true,true,()=>$("#deleteName").value===g.name))return;const i=state.games.findIndex(x=>x.id===g.id);undo={game:clone(g),index:i};state.games.splice(i,1);await saveState(state);draft=null;dirty=false;openId=null;render();toast("桌游已删除","撤销",async()=>{state.games.splice(undo.index,0,undo.game);await saveState(state);undo=null;render()});setTimeout(async()=>{if(undo?.game.id!==g.id)return;await Promise.all([g.coverId,...g.expansions.map(x=>x.coverId)].filter(Boolean).map(deleteImage));undo=null},7000);return}
 if(t==="toggle-group"){const sec=a.closest(".group"),k=`${state.view.groupBy}:${sec.dataset.group}`,s=new Set(state.view.collapsedGroups);s.has(k)?s.delete(k):s.add(k);state.view.collapsedGroups=[...s];await saveState(state);return render()}
 if(t==="rm-filter"){state.view.filters.splice(Number(a.dataset.id),1);await saveState(state);return render()}if(t==="clear-filter"){state.view.search="";state.view.filters=[];E.search.value="";await saveState(state);return render()}if(t==="rm-temp"){readFilters();tempFilters.splice(Number(a.closest("[data-frow]").dataset.frow),1);return filterRows()}
 if(t==="rename-tax"){const from=a.dataset.label,to=await promptValue("重命名标签",`“${from}”的引用会同步更新。`,from);if(!to||to===from)return;if(state.taxonomies[taxTab].includes(to))return toast("同名标签已存在，请使用合并");state.taxonomies[taxTab][state.taxonomies[taxTab].indexOf(from)]=to;migrate(taxTab,from,to);await saveState(state);categories();return render()}
 if(t==="merge-tax"){const from=a.dataset.label,list=state.taxonomies[taxTab].filter(x=>x!==from);if(!list.length)return toast("没有可合并的目标");const body=`<p>“${esc(from)}”的引用将迁移。</p><label><span>合并到</span><select id="mergeTarget">${list.map(x=>`<option>${esc(x)}</option>`).join("")}</select></label>`;if(!await ask("合并标签",body,"合并",true,true))return;const to=$("#mergeTarget").value;migrate(taxTab,from,to);state.taxonomies[taxTab]=state.taxonomies[taxTab].filter(x=>x!==from);await saveState(state);categories();return render()}
 if(t==="delete-tax"){const l=a.dataset.label;if(!await ask("删除标签",`“${l}”有 ${refs(taxTab,l)} 处引用，删除后引用变为空。`,"删除标签",true))return;migrate(taxTab,l);state.taxonomies[taxTab]=state.taxonomies[taxTab].filter(x=>x!==l);await saveState(state);categories();render()}
}
function bind(){
 E.search.oninput=async()=>{state.view.search=E.search.value;await saveState(state);render()};E.group.onchange=async()=>{state.view.groupBy=E.group.value;state.view.collapsedGroups=[];openId=null;await saveState(state);render()};E.sort.onchange=async()=>{state.view.sortBy=E.sort.value;await saveState(state);render()};E.direction.onclick=async()=>{state.view.sortDirection=state.view.sortDirection==="asc"?"desc":"asc";direction();await saveState(state);render()};
 $("#groupsButton").onclick=async()=>{const groups=buildGroups(filtered(),state.view.groupBy,state.taxonomies),collapse=!groups.every(x=>state.view.collapsedGroups.includes(`${state.view.groupBy}:${x.key}`));state.view.collapsedGroups=collapse?groups.map(x=>`${state.view.groupBy}:${x.key}`):[];await saveState(state);render()};
 $("#filterButton").onclick=()=>{tempFilters=clone(state.view.filters);filterRows();openDrawer($("#filterDrawer"))};$("#categoryButton").onclick=()=>{categories();openDrawer($("#categoryDrawer"))};$("#backupButton").onclick=()=>{backupStatus();openDrawer($("#backupDrawer"))};E.scrim.onclick=closeDrawers;$$("[data-close-drawer]").forEach(b=>b.onclick=closeDrawers);
 $("#addGameButton").onclick=newGame;$("#editModeButton").onclick=()=>editing||unlock();$("#viewModeButton").onclick=async()=>{if(dirty)return toast("请先保存或取消当前草稿");editing=false;draft=null;document.body.classList.remove("is-editing");render()};
 $("#pinForm").onsubmit=async e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();try{const pin=$("#pinInput").value,h=await hashPin(pin);if($("#pinDialog").dataset.setup==="true"){if(pin!==$("#pinConfirmInput").value)throw Error("两次输入的密码不一致");state.security.pinHash=h;await saveState(state)}else if(h!==state.security.pinHash)throw Error("密码不正确");editing=true;document.body.classList.add("is-editing");$("#pinDialog").close("ok");render()}catch(x){$("#pinError").textContent=x.message}};
 $("#addFilterButton").onclick=()=>{readFilters();const f=Object.keys(FILTER).find(k=>!tempFilters.some(x=>x.field===k));if(f&&tempFilters.length<3)tempFilters.push(defaultFilter(f));filterRows()};$("#clearFiltersButton").onclick=()=>{tempFilters=[];filterRows()};$("#applyFiltersButton").onclick=async()=>{readFilters();state.view.filters=tempFilters;await saveState(state);closeDrawers();render()};
 $("#filterRows").onchange=e=>{const r=e.target.closest("[data-frow]");if(!r)return;readFilters();const i=Number(r.dataset.frow);if(e.target.matches("[data-ffield]"))tempFilters[i]=defaultFilter(e.target.value);else if(e.target.matches("[data-fop]"))tempFilters[i].operator=e.target.value;filterRows()};
 $("#categoryTabs").onclick=e=>{const b=e.target.closest("[data-tab]");if(b){taxTab=b.dataset.tab;categories()}};$("#addCategoryForm").onsubmit=async e=>{e.preventDefault();const v=new FormData(e.currentTarget).get("label").trim();if(!v||state.taxonomies[taxTab].includes(v))return toast("标签已存在或名称为空");state.taxonomies[taxTab].push(v);await saveState(state);e.currentTarget.reset();categories();render()};
 let drag;$("#categoryList").ondragstart=e=>drag=Number(e.target.closest("[data-ci]")?.dataset.ci);$("#categoryList").ondragover=e=>e.preventDefault();$("#categoryList").ondrop=async e=>{e.preventDefault();const to=Number(e.target.closest("[data-ci]")?.dataset.ci);if(!Number.isInteger(drag)||!Number.isInteger(to)||drag===to)return;const l=state.taxonomies[taxTab],[x]=l.splice(drag,1);l.splice(to,0,x);await saveState(state);categories();render()};
 $("#exportButton").onclick=async()=>{await exportNow();toast("完整备份已导出")};$("#importInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;if(draft){toast("请先保存或取消当前编辑");e.target.value="";return}if(!editing&&!await unlock()){e.target.value="";return}try{const p=await readBackupFile(f),s=summarizeBackup(p),body=`<p>备份时间：${new Date(s.exportedAt).toLocaleString("zh-CN")}<br>桌游：${s.games} 款<br>扩展：${s.expansions} 个<br>电子游戏：${s.screenGames} 款<br>图片：${s.images} 张</p><p>${p.hasScreenData?"一桌与一屏将被完整替换。":"旧版桌游备份将保留现有电子游戏及其封面。"}恢复前会自动导出当前完整备份。</p>`;if(!await ask("完整恢复备份",body,"恢复备份",true,true))return;await exportNow("一桌一屏-恢复前自动备份");state=await restoreBackup(p);editing=false;document.body.classList.remove("is-editing");openId=openGroup=null;closeDrawers();options();render();toast("备份已完整恢复")}catch(x){toast(`恢复失败：${x.message}`)}finally{e.target.value=""}};
 document.onclick=click;document.addEventListener("input",e=>{if(e.target.closest("#gameEditor")){readForm();autosave()}});document.addEventListener("change",e=>{if(e.target.matches("[data-file]")&&e.target.files[0])image(e.target.files[0],e.target.dataset.file)});document.addEventListener("dragover",e=>{const d=e.target.closest("[data-drop]");if(d){e.preventDefault();d.classList.add("is-dragging")}});document.addEventListener("dragleave",e=>e.target.closest("[data-drop]")?.classList.remove("is-dragging"));document.addEventListener("drop",e=>{const d=e.target.closest("[data-drop]");if(d){e.preventDefault();d.classList.remove("is-dragging");if(e.dataTransfer.files[0])image(e.dataTransfer.files[0],d.dataset.drop)}});document.addEventListener("paste",e=>{const f=[...e.clipboardData.files].find(x=>x.type.startsWith("image/")),d=document.activeElement.closest?.("[data-drop]");if(f&&d)image(f,d.dataset.drop)});
 $("#gameEditor")?.addEventListener("submit",e=>{e.preventDefault();saveGame()});
}
document.addEventListener("submit",e=>{if(e.target.id==="gameEditor"){e.preventDefault();saveGame()}});
async function init(){state=await loadState();options();bind();backupStatus();render();const last=state.meta.lastBackupAt?new Date(state.meta.lastBackupAt).getTime():0;if(state.games.length&&new Date(state.meta.updatedAt).getTime()>last&&Date.now()-last>30*864e5)toast("收藏已超过 30 天没有完整备份","去备份",()=>openDrawer($("#backupDrawer")))}
init().catch(e=>{console.error(e);E.collection.innerHTML=`<div class="empty-collection"><div><h2>收藏无法载入</h2><p>${esc(e.message)}</p></div></div>`});
